### ISSUE TITLE
3.0.0-0 hangs on clearning dalvik/cache

### ISSUE THREAD

**Issue by xenithorb** [TeamWin/android_device_oneplus_bacon#8]
Hanging on:

```
Formatting Cache using make_ext4fs...
```

**Comment by xenithorb** [comment]
Hello is this in the right place? Can I assist somehow?

**Comment by maximilianKoeper** [comment]
I think they have fixed the Problem in the new Version for the OPO. (3.0.0-1)
On my device it works now.

**Comment by xenithorb** [comment]
Do you guys watch this repo at all? I'm closing the issue because I believe it to be fixed (for me) in 3.0.0-1
